
/**
 * 事件名定义
 */

export enum EventName  {

    UI_OPEN_PANEL           = 'UI_OPEN_PANEL',
    UI_CLOSE_PANEL          = 'UI_CLOSE_PANEL',
    EVENT_LOADED_MODULE     = 'EVENT_LOADED_MODULE',
    EVENT_MSGBOX_ERROR      = 'EVENT_MSGBOX_ERROR',//错误码
    EVENT_PLAYER_EXP_CHANGE = 'EVENT_PLAYER_EXP_CHANGE',//人物经验变化
    EVENT_PLAYER_RAND_SKILL = 'EVENT_PLAYER_RAND_SKILL',
}

